<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function moliek_theme($existing, $type, $theme, $path): array {
  return [
    'moliek_theme' => [
      'variables' => [
        'text' => NULL,
        'form' => NULL,
        'cats' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function moliek_form_moliek_CatForm_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'moliek/ajax-patch';
}
